CREATE SCHEMA NIKONOOK;
USE NIKONOOK;

CREATE TABLE Menu (
MenuName VARCHAR(64) NOT NULL,
PRIMARY KEY (MenuName)
);

CREATE TABLE Menu_Item (
ItemName VARCHAR(64) NOT NULL,
Description VARCHAR(512) NOT NULL,
Price DECIMAL(5, 2) NOT NULL,
Category VARCHAR(64) NOT NULL,
PRIMARY KEY (ItemName)
);

CREATE TABLE Ingredient (
IngredientName VARCHAR(64) NOT NULL,
QuantityInStock DOUBLE NOT NULL,
UnitOfQuantity VARCHAR(64) NOT NULL,
PRIMARY KEY (IngredientName)
);

CREATE TABLE Employee (
EmployeeID INT NOT NULL,
EmployeeName VARCHAR(64) NOT NULL,
PRIMARY KEY (EmployeeID)
);

CREATE TABLE Dining_Table (
TableID INT NOT NULL,
Status VARCHAR(64) NOT NULL,
Capacity INT NOT NULL,
EmployeeID INT NOT NULL,
OrderID INT NOT NULL,
Date DATE NOT NULL,
Time TIME NOT NULL,
PRIMARY KEY (TableID),
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
ON DELETE RESTRICT ON UPDATE CASCADE,
UNIQUE (OrderID)
);

CREATE TABLE Manages (
ManagerID INT NOT NULL,
EmployeeID INT NOT NULL,
PRIMARY KEY (ManagerID, EmployeeID),
FOREIGN KEY (ManagerID) REFERENCES Employee(EmployeeID)
ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Menu_Connector (
MenuName VARCHAR(64) NOT NULL,
ItemName VARCHAR(64) NOT NULL,
PRIMARY KEY (MenuName, ItemName),
FOREIGN KEY (MenuName) REFERENCES Menu(MenuName)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ItemName) REFERENCES Menu_Item(ItemName)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Recipe (
ItemName VARCHAR(64) NOT NULL,
IngredientName VARCHAR(64) NOT NULL,
IQuantity DOUBLE NOT NULL,
PRIMARY KEY (ItemName, IngredientName),
FOREIGN KEY (ItemName) REFERENCES Menu_Item(ItemName)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IngredientName) REFERENCES Ingredient(IngredientName)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Ordered_Item (
OrderID INT NOT NULL,
ItemName VARCHAR(64) NOT NULL,
MQuantity INT NOT NULL,
PRIMARY KEY (OrderID, ItemName),
FOREIGN KEY (OrderID) REFERENCES Dining_Table(OrderID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ItemName) REFERENCES Menu_Item(ItemName)
ON DELETE CASCADE ON UPDATE CASCADE
);
